spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5435/todo
    username: todo
    password: todo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
